apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-apigwws
  namespace: argocd
spec:
  project: default
  source:
    path: deploy/k8s/helm/apigwws
    repoURL: https://github.com/andrewhaine1/eShopOnContainers
    targetRevision: HEAD
    helm:
      releaseName: eshop-apigwws
      valueFiles:
        - ../app.yaml
        - ../inf.yaml
        - ../ingress_values.yaml
          #      valuesObject:
          #        app:
          #          name: eshop
          #        inf:
          #          k8s:
          #            dns: ""
          #          registry:
          #            server: kubeclusteracr.azurecr.io
          #            secretName: acr-secret
          #        image:
          #          tag: linux-latest
          #          pullPolicy: Always
          #        ingress:
          #          enabled:
          #            true
          #          tls:
          #            hosts:
          #              - "eshop.kubeapps.co.za"
          #            secretName: eshop-webspa-tls-secret
        
  destination:
    server: https://10.0.2.4:6443
    namespace: eshop
