apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-keystore-data
  namespace: argocd
spec:
  project: default
  source:
    path: deploy/k8s/helm/keystore-data
    repoURL: https://github.com/andrewhaine1/eShopOnContainers.git
    targetRevision: HEAD
    directory:
      recurse: true
    helm:
      valueFiles:
      - deploy/k8s/helm/app.yaml
      - deploy/k8s/helm/inf.yaml
      - deploy/k8s/helm/ingress_values.yaml
  destination:
    server: https://10.0.2.4:6443
    namespace: eshop
