apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-keystore-data
  namespace: eshop
spec:
  project: default
  source:
    path: deploy/k8s/helm/keystore-data
    repoURL: https://github.com/andrewhaine1/eShopOnContainers
    targetRevision: dev
    directory:
      recurse: true
    helm:
      releaseName: keystore-data
      valueFiles:
      - deploy/k8s/helm/app.yaml
      - deploy/k8s/helm/inf.yaml
      - deploy/k8s/helm/ingress_values.yaml
  destination:
    server: kubeapps-abm-cluster
    namespace: eshop
