apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"configManagementPlugins":"- name: kustomized-helm\n  init:\n    command: [\"/bin/sh\", \"-c\"]\n    args: [\"helm dependency build || true\"]\n  generate:\n    command: [\"/bin/sh\", \"-c\"]\n    args: [\"helm template ../../helm_base --name-template $ARGOCD_APP_NAME --include-crds \u003e ../../helm_base/all.yml \u0026\u0026 kustomize build\"]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-08-08T10:49:26Z","labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd","resourceVersion":"217212","uid":"6b493072-5d85-4b06-949f-4f79bb3a2cbd"}}
  creationTimestamp: "2024-08-08T10:49:26Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "953535"
  uid: 6b493072-5d85-4b06-949f-4f79bb3a2cbd
