replicaCount: 1
clusterName: eshop-aks
pathBase: /

image:
  repository: eshop/webspa
  tag: linux-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Set allowed upload size to 10GB, which is way too big
    #nginx.ingress.kubernetes.io/proxy-body-size: "10000000000"
    #nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    #nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    #nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    #ngressclass.kubernetes.io/is-default-class: "true"
  tls: 
    hosts:
      - "eshop.kubeapps.co.za"
    secretName: eshop-webspa-tls-secret

ingressHosts:
    #- host: eshop.kubeapps.co.za
    #  paths:
    #  - path: "/"
  - "eshop.kubeapps.co.za"

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: DPConnectionString
      key: webspa__keystore
    - name: PurchaseUrl
      key: urls__apigwws
    - name: CallBackUrl
      key: urls__spa
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: IdentityUrlHC
      key: internalurls__identity__hc      
    - name: SignalrHubUrl
      key: urls__apigwws
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: ASPNETCORE_URLS
      value: http://0.0.0.0:80
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'

