# This file contains common ingress annotations when using AKS with Http Application Routing

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
      #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
