apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-sql-data
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: deploy/k8s/helm/sql-data
    repoURL: https://github.com/andrewhaine1/eShopOnContainers
    targetRevision: HEAD
    helm:
      releaseName: eshop-sql-data
      valueFiles:
        - ../app.yaml
        - ../inf.yaml
        - ../ingress_values.yaml
      valuesObject:
        image:
          tag: latest
          pullPolicy: Always        
          #      valuesObject:
          #        inf:
          #          registry:
          #            server: kubeclusteracr.azurecr.io
          #            secretName: acr-secret
          #        image:
          #          tag: linux-latest
          #          pullPolicy: Always
  destination:
    server: https://10.0.2.4:6443
    namespace: eshop
