{{- if .Values.ingress.enabled -}}
{{- $ingressPath := include "pathBase" . -}}
{{- $serviceName := $.Values.app.svc.spa -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "webspa.fullname" . }}
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if and .Values.inf.tls.enabled .Values.inf.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.inf.tls.issuer }}
{{- end }}
{{- if .Values.inf.mesh.enabled }}
{{- with .Values.ingress.mesh.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  ingressClassName: nginx
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- range .Values.ingressHosts }}
      - {{ . }}
    {{- end }}
    secretName: eshop-webspa-tls-secret
{{- end }}
  rules:
  {{- range .Values.ingressHosts }}
    - host: {{ . }}
      http:
        paths:
        - path: {{ $ingressPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ $serviceName }}
              port:
                number: 80
  {{- end }}
{{- end }}
