apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-nosql-data
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: deploy/k8s/helm/nosql-data
    repoURL: https://github.com/andrewhaine1/eShopOnContainers
    targetRevision: HEAD
    helm:
      releaseName: nosql-data
      valueFiles:
      - ../app.yaml
      - ../inf.yaml
      - ../ingress_values.yaml
  destination:
    server: https://10.0.2.4:6443
    namespace: eshop
